matrix:
  include:
    - language: node_js
      node_js:
        - "iojs"
        - "7"
      before_script:
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
    - language: python
      python:
        - "3.5"
  
