matrix:
  include:
    - language: node_js
      node_js:
        - "7"
    - language: python
      python:
        - 3.5
      env:
        - DJANGO=1.11
      before_install:
        - export DJANGO_SETTINGS_MODULE=Open_Survey.settings
        - export PYTHONPATH=$HOME/builds/KevinOrtiz/Proyecto_Integradora_Survey_Open_Source
        - export PIP_USE_MIRRORS=true
      install:
        - pip install django==$DJANGO --quiet
        - pip install psycopg2 --quiet
  
